# Generated by Django 3.0.5 on 2020-04-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Месяц')),
                ('Year', models.CharField(max_length=4, verbose_name='Год')),
                ('Income', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Чистый доход')),
            ],
            options={
                'verbose_name': 'Показатель эффективности',
                'verbose_name_plural': 'Показатели эффективности',
            },
        ),
    ]
